name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@v1

      - name: Create test tar
        run: yarn run test-create-data

      - uses: blacha/hyperfine-action@v1